### ISSUE TITLE
Form / food preselection

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#1]
## Value Proposition

- As a user conscious to health and the environment
- I want to get information on what are the consumption recommendations of the food that I eat in a day,
- to be able to get a better understanding of overall dietary guidelines of the Planetary Health Diet

## Description

![Image](https://user-images.githubusercontent.com/123627153/227513179-fb8766f6-7328-4017-8cd8-c701c3b99554.png)

## Acceptance criteria

- [ ] The form page has the question "Bitte wähle aus, was du heute gegessen hast"
- [ ] Out of 3 categories only one can be selected/toggled
- [ ] By clicking on the button, the heading "Empfohlener Tagesbedarf" and the recommendation for the selected food appears, the form is not automatically reset
- [ ] If nothing is chosen, this part will remain empty
- [ ] Upon click of the reset button, the selection is reset

## Tasks

- [x] Create branch
&nbsp;
- [x] Global Styles
&nbsp;
- [x] Create components/Form
incl. toggle-input fields, submit-button and reset-button
&nbsp;
- [x] Create db.js with foods-Array and 3 foods
(including name, recommendedConsumption, recommendedExample)
- [x] Import foods-Array to Form-component 
- [x] Dynamically link with form, so that radio buttons are based on the array (key name)  and below the form it renders the required information from the array (key recommendedConsumption, recommendedExample) based on the selection (using useState, map)
&nbsp;
- [x] Import Form-component to index.js and render
&nbsp;
- [x] Add to app
- [x] Write tests that check, whether when a certain food is chosen/input is selected, the recommendedConsumption and recommendedExample corresponds with the selected food
