### ISSUE TITLE
Add start page and navigation

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#10]
## Value Proposition

- As a user,
- I want to be able to always navigate back to the homepage
- in order to restart the food quiz

## Description

![Image](https://user-images.githubusercontent.com/123627153/230325430-44250bbd-e144-47b7-a057-fcb9ef3da565.png)

## Acceptance criteria

- [ ] When I open the app, I see a startpage
- [ ] The startpage includes a short introduction and a button to start the daily food quiz
- [ ] Throughout the app, I have a navbar with a Home-Button, so that on every page that follows, I am able to navigate back to the startpage

## Tasks

- [ ] Create branch
&nbsp;
- [ ] Move the first page of the quiz from pages/index.js to something like pages/select-food-categories/index.js"
- [ ] In pages/index.js render p-tag with intro-text and BasicButton-component with text "Starte dein tägliches Essensquiz"
&nbsp;
- [ ] Create components/Navbar/Navbar.js and style
- [ ] Create components/Navbar/NavBarLink and style, import and render in Navbar-component (however, might not be necessary to create extra-component and be able to directly render in Navbar.js)
- [ ] Render navbar in components/layout.js
&nbsp;
- [ ] Change href of RestartQuizLink-component from "/" to "/detailsformpage"
&nbsp;
- [ ] Write tests, testing that the button and footer with navbar are rendered

**Comment by Sascha-Pionczewski** [comment]
lgtm

**Comment by alexWaligorski** [comment]
Alina, this story is very well written and makes a lot of sense!
I have only one remark: I find it a bit confusing to see "Tagesscore" on the startig page... because my last Quiz might be at least a day in the past. So, why not changing it to e.g.: "Dein letzter Tagesscore"
This way you have a Tagesscore or aktueller Score on the resultpage and some kind of "legacy score" on the homepage

**Comment by alinawinter** [comment]
Oh you are right, that absolutely makes sense :D

**Comment by alinawinter** [comment]
Incorporated that into the text!
