### ISSUE TITLE
Add detail results to score page

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#12]
## Value Proposition

- As a user,
- I want to be able to see in how far my eating habits are in accordance with the Planetary Health Diet with regard to the individual food categories
- to be able to adapt my eating habits where necessary

## Description

![Image](https://user-images.githubusercontent.com/123627153/231168635-3330ed99-28e1-4ab8-9357-8e57fea08793.png)

## Acceptance criteria

- [ ] When I click on the button "Details zeigen" a table pops up below the button
- [ ] The table contains the following information for each food category (not only the ones that have been previously selected): score, consumed quantity and recommended quantity, including an example to show how much that would be
- [ ] The button has changed from "Details zeigen" zu "Details ausblenden", clicking on it again will hide the results as before

## Tasks

- [ ] Create branch "detail-results-scorepage"
&nbsp;
- [ ] Change components/score/Score.js to OverallScore.js
- [ ] Create components/score/DetailScore.js
- [ ] Add a section with a table with all foodCategories in it, have it dynamically fill with the information from the foodCategories array as well as the selectedFoodCategories array using template strings (try and use map for that)
- [ ] hide the section on default, probably using state with a showResult-variable on false
- [ ] Add button that upon click toggles the state variable and changes its text
&nbsp;
- [ ] Import to pages/scorepage/index.js and render
&nbsp;
- [ ] Write tests, testing that the detail results are shown on button click

**Comment by toshydev** [comment]
LGTM! ✅

**Comment by alexWaligorski** [comment]
A great feature and a well written story! After reading through the past several US I feel, that all these amazing stats of the personal food intake really need a dedicated space in your app. Please don' hide them behing a "show more" button 😀 
Of course this is your choice. Just wanted to say: I am a big fan and think a stats page would be super fancy!

**Comment by alinawinter** [comment]
Okay thats a good idea, to do a specific page for it :-D I have to see how much time I have left, even for this simplified version of it. But I really hope I can do it, because only then all the quizzes really make sense :D
