### ISSUE TITLE
Add 7 daily quiz option to start page

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#15]
## Value Proposition

- As a user,
- I want to be able to do quizzes on 7 days of a week and save my scores
- in order to have an overview over my scores and better monitor my eating habits

## Description

![Image](https://user-images.githubusercontent.com/123627153/232454083-bc2fe244-607c-4cb5-a203-f33ae26bb837.png)

## Acceptance criteria

- [x] On the startpage I have the option for monday till sunday to start a daily quiz
- [x] When the quiz is finished, I can restart the quiz and the current score is displayed below this button

## Tasks

- [x] Create branch
&nbsp;
- [x] Add headings with monday-sunday to startpage and a restart-quiz-button each, structure and style
- [x] Implement logic to save all scores to the local storage (probably save as an array)
- [x] Optionally create a reset button, to reset all quizzes at once

**Comment by alinawinter** [comment]
## Value Proposition

- As a user,
- I want to be able to do quizzes on 7 days of a week and save my scores
- in order to have an overview over my scores and better monitor my eating habits

## Description

![Image](https://user-images.githubusercontent.com/123627153/232454083-bc2fe244-607c-4cb5-a203-f33ae26bb837.png)


## Acceptance criteria

- [ ] On the startpage I have the option for monday till sunday to start a daily quiz
- [ ] When the quiz is finished, I can restart the quiz and the current score is displayed below this button


## Tasks

- [ ] Create branch
&nbsp;
- [ ] Add headings with monday-sunday to startpage and a restart-quiz-button each, structure and style
- [ ] Implement logic to save all scores to the local storage (probably save as an array)

**Comment by alinawinter** [comment]
Thank you Alex <3

**Comment by XxKikoxX** [comment]
My food score is miserable ^^.
No matter what I enter, I don't get below 6%. But I think this app could help people pay more attention to their eating habits. Especially people who eat a lot in between meals may be encouraged to reconsider their habits and possibly benefit from it in terms of health.
