### ISSUE TITLE
Add weekly score

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#16]

**Comment by alinawinter** [comment]
## Value Proposition

- As a user,
- I want to be able to view my weekly score based on the food that I ate during the week
- in order to get a realistic idea in how far my eating habits correspond to the Planetary Health Diet

## Description

![Image](https://user-images.githubusercontent.com/123627153/232454083-bc2fe244-607c-4cb5-a203-f33ae26bb837.png)


## Acceptance criteria

- [ ] On the startpage I have the option for monday till sunday to start a daily quiz
- [ ] Whenever I finish one quiz, the weekly score automatically updates (it is calculated in the way that we have a weekly expected consumption for every food category (daily consumption x 7). The consumptions per food category within a week are added up across all quizzes. We then calculate the deviation and accordance between the sum of recommended weekly and actual weekly consumption. Hence, the weekly score is not calculated as an average of all daily scores)


## Tasks

- [ ] Create branch
&nbsp;
- [ ] Add headings with monday-sunday to startpage and a restart-quiz-button each, structure and style
- [ ] Implement logic to save all scores to the local storage (probably save as an array)

**Comment by alexWaligorski** [comment]
Hmm.. I am not quite sure how this feature works. I am really bad at math :( Anyways: I find it a bit confusing to unserstand where the weekly score is displayed. Is it below the week-list? Maybe add a section / card with a heading to make it a bit clearer or another page for the weekly score. Might be also interesting to have a little text explaining the specifics of the weekly score. I think there is nothing wrong with this user story per se apart from maybe a missing sentence on WHERE this score will be displayed.

**Comment by alinawinter** [comment]
I wanted to do it like in the picture - below the start-quiz-buttons with a heading, I thought I dont have to include it into the text then but I did now to make it clearer! Thank you :-)
