### ISSUE TITLE
Form / quantitiy specification

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#2]
## Value Proposition

- As a user conscious to health and the environment
- I want to get information on, whether my individual amount of the selected food (in grams)
corresponds with the recommendations of the Planetary Health Diet
- in order to get an idea of whether I eat too much or too little of it

## Description

![Bildschirmfoto 2023-04-03 um 16 25 30](https://user-images.githubusercontent.com/123627153/229539179-f2a3b446-4fd9-4aa9-98c3-02c6b10e6dcb.png)

## Acceptance criteria

- [x] By clicking on the button "Weiter" on screen 1, screen 2 appears (this is only possible if a food has been selected)
- [x] Screen 2 shows the food that the user selected
- [x] The user can use the range slider to choose his consumption of it in grams
- [x] When clicking the button "Auswertung", the user gets information on to how many percent 
his consumption corresponds with the recommendation

## Tasks

- [x] Create branch
&nbsp;
- [x] Extent the foods-Array in the db.js with necessary information on range
&nbsp;
- [x] Create components/FormQuantitySpecification incl. range-input and submit-button
- [x] Import foods-Array
- [x] Create pages/FormDetailspage.js
- [x] Import created component to FormDetailspage.js and render it
- [x] Create "Zurück zur Auswahl"- button/Link on FormDetailspage to index.js
&nbsp;
- [x] Create additional submit-button "Weiter" to components/FormFoodPreselection that leads to screen 2 (history.push), that requires the selection of a radio button
&nbsp;
- [x] Create Link between both components (the formData from the first component can be passed as prop to the second component, probably it will be necessary to create a global state)
- [x] Use formData and foods-Array to build the forms label and input field
- [x] Use formData and foods-Array to add functionality to the form so that upon submit below the form it renders the required information (decide whether to create a utils-function for the percentage calculation)
&nbsp;
- [x] Add to app
- [x] Write tests, testing different input to the range-slider and whether the result given out upon submit is correct

**Comment by alinawinter** [comment]
Thank you for your feedback! :-) it is highly appreciated! :-) 

I Included almost all your suggestions, Alex. 
- For the third point, this function is part of another task and i tried to make clearer that it is part of it. Hope, that it is clearer now. 
- As for the second suggestions, I really want to have the range-slider, so I'm sticking with that :-P 

regarding your suggestions, Nina:
- after speaking with Paul, the other food categories should rather be added separately in the next user story
- I think I understand what you mean but doesn't make sense for how the project will go further (after the user gave all his/her information, he/she is supposed to receive a score), thank you for your idea anyway :-)
- Yes, on screen 2, there is the button "Zurück zur Auswahl" to get back to the first screen

**Comment by PReichetanz** [comment]
Nice work, just one thought as Alex mentioned it: consider to postpone the tool tip for now and just concentrate on the new page + the calculation of the result.
