### ISSUE TITLE
Add new home page and navbar

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#20]
## Value Proposition

- As a user,
- I want to be able to see at first glance, whether I already took the daily quiz and based on that info have the option to take the quiz or get an overview over my week and weekly scores

## Description

![Image](https://user-images.githubusercontent.com/123627153/233021824-7811fae0-9c36-4809-aaaa-a2983ea87f57.png)

## Acceptance criteria

- [ ] When I open the app, a start page with a short intro-text and button appear
- [ ] The text of the button depends on, whether I already took the quiz today. If it's been taken it will change from "Starte dein tägliches Essensquiz" to "Zur Wochenübersicht" - a Link to the overview
- [ ] The navbar allows the user to navigate between Home and the week overview (this navbar will disappear, when the quiz is taken)

## Tasks

- [ ] Create branch
&nbsp; 
- [ ] Move pages/index.js content to new pages/weeklyoverview/index.js (change imports)
- [ ] create components/navbar with links to Home and the weekly overview
- [ ] Render p-Element and 2 optional buttons on startpage
- [ ] Probably use "const today = new Date().getDay()" to get the current day and based on that render either button 1 or 2 on startpage

**Comment by rabe200** [comment]
lgtm
just because i had to reread a few times to correctly understand:
maybe set "navbar will disappear, when the quiz is taken" to a separate acceptance criteria :)

**Comment by alinawinter** [comment]
you're right @rabe200, I changed that :-D
