### ISSUE TITLE
Add navbar and info page

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#21]
## Value Proposition

- As a user,
- I want to be able to navigate between pages and to an info-page, where I get information on the planetary health diet
- in order to understand its goals and the goal of the app

## Description

![Image](https://user-images.githubusercontent.com/123627153/233953508-f25d3cff-b6f6-41ac-b19b-c2a8aab686be.png)

## Acceptance criteria

- [ ] there is a navbar with a link to the info-page
- [ ] the navbar allows the user to navigate between Home, info and score
- [ ] upon-click a page with info opens

## Tasks

- [ ] Create branch
&nbsp; 
 - [ ] Move pages/index.js content to new pages/weeklyoverview/index.js (change imports)
 - [ ] create components/navbar with links to Home/weekly overview and score
&nbsp; 
- [ ] Create pages/infopage/index.js
- [ ] Fill with some information
- [ ] Add info-link to navbar

**Comment by rabe200** [comment]
lgtm :)
