### ISSUE TITLE
Increase usability of app

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#25]
## Value Proposition

- As a user,
- I want to be able to get a good user experience on different screen formats and over different periods of time without distortions or error messages

## Description

- Making the app responsive on different screen formats
- Implementing additional tests to make app maintainable

## Acceptance criteria

- [ ] The app looks good on mobile, tablet and screen
- [ ] There are additional simple tests for the infopage, weeklyoverview and scorepage

## Tasks

- [ ] Create branch
&nbsp; 
- [ ] Add media queries to styles.js
- [ ] Write tests for infopage, weeklyoverview and scorepage

**Comment by onemanwenttomow** [comment]
I feel like both of these goals are very admirable. 
 
* providing a responsive website across multiple devices. 
* writing additional tests to reduce errors 

This probably doesn't fall under a normal User Story, and you can just move on to directly creating a branch and then a pull request. I would advise 2 different pull requests here. One for the responsive design and one for the additional tests for the app.
