### ISSUE TITLE
Extent foods array

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#3]
## Value Proposition

- As a user conscious to health and the environment
- I want to get information on what are the consumption recommendations of ALL the food that I eat in a day,
- to be able to get a better understanding of overall dietary guidelines of the Planetary Health Diet

## Description

![Image](https://user-images.githubusercontent.com/123627153/227561287-25e8a547-9fd6-4283-bb1f-6b8479aa95fd.png)

## Acceptance criteria

- [ ] 13 food categories appear on the screen and only one can be selected/toggled
- [ ] By clicking on the button, the heading "Empfohlener Tagesbedarf" and the recommendation for the selected food appears, the form is not automatically reset
- [ ] If nothing is chosen, this part will remain empty
- [ ] Upon click of the reset button, the selection is reset

## Tasks

- [ ] Create branch

- [ ] Extent the array with 10 further foods array in the db.js (incl. name, recommendedConsumption, recommendedExample,
range, rangeExamples etc.)

**Comment by supernova-97** [comment]
Very precise, nothing to add 👍🏻

**Comment by alinawinter** [comment]
That's a good point, Jin. I think, I will try out both and see what looks better. Thank you :-)
