### ISSUE TITLE
Add tooltip to range-slider

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#4]
## Value Proposition

- As a user
- I would like to receive examples of how many grams correspond to which everyday quantities that I know
- to be able to better estimate how many grams of food I consumed

## Description

![Image](https://user-images.githubusercontent.com/123627153/227565677-fb384969-1b67-4ec8-8b87-5e678ad5e7c3.png)

## Acceptance criteria

- [ ]  The user can use the range slider to choose his consumption of it in grams
- [ ]  Directly below the range slider, the user gets information/a tooltip on everyday quantities to help estimate his
consumption
- [ ] For each food there should be about 3-4 breakpoint-bubbles, at which this info appears

## Tasks

- [ ] Create a new branch
&nbsp;
- [ ] Extent the foods-Array in the db.js with information on different everyday quantities for the foods
 &nbsp;
- [ ] Add functionality to the range-slider, so that when moving the slider, everyday quantities are shown using formData and the foods-Array (probably using an EventListener and threshold-logic)
&nbsp;
- [ ]  Write tests, testing different input to the range-slider and whether the tooltip correctly appears with the correct information

**Comment by Efendi5** [comment]
Thats a good user story and the Acceptance criteria are plausible

**Comment by LuYujin9** [comment]
I like the way you wrote the tasks, very detailed and easy to understand.
