### ISSUE TITLE
Add score page

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#6]
## Value Proposition

- As a user, after typing in the information on what I ate, 
- I want to see a score page that gives me information on, in how far my individual amount of the selected food (in grams)
corresponds with the recommendations of the Planetary Health Diet
- in order to get an idea of whether I eat too much or too little of it

## Description

![Image](https://user-images.githubusercontent.com/123627153/229077791-8bdebc58-7464-4e02-83c6-c0e3301d139f.png)

## Acceptance criteria

- [x] After typing in the consumption of a specific food, by clicking on the button "Auswertung" on screen 1, screen 2 appears
- [x] Screen 2 shows a score page that shows to how many percent the typed in consumption corresponds with the recommended amount
- [x] When clicking the button "Zurück zum Start" the user can go back to the beginning of the quiz

## Tasks

- [x] Create branch
&nbsp;
- [x] Create pages/ScorePage.js
- [x] Create components/Score.js and import into ScorePage, render
- [x] Make the "Auswertung"-submit-button on pages/FormDetailspage.js be at the same time a link to the scorepage
- [x] Create button "Zurück"- button/Link on scorePage to FormDetailspage
&nbsp;
- [x] Import foods-Array to ScorePage/score-component
- [x] Move function that calculates score from previous page to ScorePage/score-component
- [x] Transfer the form data to ScorePage/score-component (with global state) 
- [x] Make the ScorePage (Score-component) dynamically change based on the respective formData
&nbsp;
- [x] Add to app
- [x] Write tests, testing input to the range-slider and whether the result given out upon submit is correct on the scorePage
