### ISSUE TITLE
Allow selection of more than one foodCategory

### ISSUE THREAD

**Issue by alinawinter** [alinawinter/capstone-project#7]
## Value Proposition

- As a user,
- I want to give information on SEVERAL of the food that I ate and receive back information on in how far my overall consumption of that food corresponds with the recommendations of the Planetary Health Diet
- in order to get an idea of to what extent the ratios of my habits and the diet match

## Description

<img width="580" alt="Bildschirmfoto 2023-04-11 um 12 56 11" src="https://user-images.githubusercontent.com/123627153/231139906-cd7486d2-d658-41f0-9e40-ab0b467271f9.png">

## Acceptance criteria

- [x] On screen 1, the user is able to choose more than one food category
- [x] If the user clicks "Weiter", for each category that was chosen a detailspage is shown, where the user can now type in his/her amount of consumption for the respective food (screen 2 and screen 3)
- [x] After going through all the detailspages, screen 4 shows a score page that shows to how many percent the typed in consumption corresponds with the recommended amount
- [x] When clicking the button "Zurück zum Start", the user can go back and restart the quiz from the beginning

## Tasks

- [x] Create branch
&nbsp;
- [x] Change input from radio buttons to checkboxes in the FormPreselection-component
- [x] use map and slug to give out several detailspages
&nbsp;
- [x] collect formdata from detailspages as objects in new array that has a global state
&nbsp;
- [x] link last detailspage to the scorepage
- [x] on the scorepage, import the new array (array with information on food categories and recommendations regarding the Planetary Health Diet from the database should already have been imported to the scorepage)
- [x] Write/add utils-function that based on that information calculates an average/overall match score for the selected food (probably before that write a function that matches the information from the new array with the information from the database)
&nbsp;
- [x] Write tests, testing selection and input to the range-slider and whether the result given out upon submit is correct on the scorePage

**Comment by lenzloesche** [comment]
hi,
great. I understand everything, but have 2 remarks:
- the "I want to" in the value proposition is worded a bit complicated. I think you go for easier language here.
- secondly, you don't write where you get the Planetary Health Diet information from. Is it an api or how do you get it? This is important because the user story should be able to be read and coded by someone else(maybe you already have this data in your project, I don't know, just a thought).

**Comment by alinawinter** [comment]
Hello @lenzloesche, thank you for your comment! :-) 
I will try and incorporate that into the user story!

**Comment by Gblur** [comment]
Very nice perfect flow.!!
